# fly.toml app configuration file generated for fullstackopen-part11-jk on 2023-07-18T17:11:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-part11-jk"
primary_region = "lax"

[deploy]
  release_command = "pnpm build"

[processes]
  app = "pnpm start-prod"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"