name: Periodic Health Check

on:
  schedule:
    - cron: '30 17/1 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://fullstackopen-part11.com
      - name: Discord success
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: Github Health Check
          details: https://fullstackopen-part11.onrender.com is looking good.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          username: Github Health Check
          details: https://fullstackopen-part11.onrender.com isn't feeling too well...
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
