name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    if: contains(join(toJson(github.event.commits.*.message)), '#skip') != true
    steps:
      - name: commit messages
        run: echo "Test"
